name: form_handling
description: A starting point for Dart libraries or applications.
version: 2.0.0

environment:
  sdk: "^3.9.0"

dependencies:
  dart_either: ^2.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  json_serializable: ^6.11.0
  lint: ^2.8.0
  pedantic: ^1.11.1
