name: form_handling
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dartz: ^0.10.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  freezed_annotation: ^2.0.3

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3
  json_serializable: ^6.2.0
  lint: ^1.8.2

flutter:
