name: form_handling
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dartz: ^0.10.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.0-dev.7
  freezed_annotation: ^0.14.2

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  json_serializable: ^4.1.4
  lint: ^1.6.0

flutter:
